name: python_packages
channels:
- defaults
- conda-forge
- anaconda
- javascript
dependencies:
- python<3.8
- nodejs<13
- gdal
- geopandas
- pip
- pip:
  - --editable extra_utils_pckg
  - --editable spatial_utils_pckg
  - --editable cx_ora_spatial_pckg
  # - --requirement file:requirements.txt